### ISSUE TITLE
access to panel no error but can't logged in

### ISSUE THREAD

**Issue by Owned67** [nikitavondel/steam-ts#27]
> npm start

> steam-ts@1.3.4 start G:\GitHub\steam-ts
> node lib/launch.js

Trying to connect to the TeamSpeak server...
Logged into the query with credentials.
Using virtual server 1 now.
Changed query client name.
Succesfully launched the bot.
Admin panel available on port: 8080
GET / 302 10.081 ms - 56
GET /login 304 7.722 ms - -
GET /stylesheets/bootstrap.min.css 304 7.911 ms - -
GET /stylesheets/ie10-viewport-bug-workaround.css 304 33.177 ms - -
GET /stylesheets/signin.css 304 32.147 ms - -
GET /stylesheets/sticky-footer.css 304 33.036 ms - -
GET /stylesheets/toastr.min.css 304 33.269 ms - -
GET /javascripts/jquery.min.js 304 32.830 ms - -
GET /javascripts/ie10-viewport-bug-workaround.js 304 1.125 ms - -
GET /javascripts/socket.io-1.4.5.js 304 1.633 ms - -
GET /javascripts/toastr.min.js 304 2.674 ms - -
GET /javascripts/login.js 304 3.452 ms - -
GET /fonts/glyphicons-halflings-regular.woff2 304 0.232 ms - -
GET /index 404 3.362 ms - 887
GET /favicon.ico 404 1.287 ms - 887
Successfully queried users and updated userdata.
GET /login 304 5.209 ms - -
GET /stylesheets/bootstrap.min.css 304 19.566 ms - -
GET /stylesheets/ie10-viewport-bug-workaround.css 304 34.131 ms - -
GET /stylesheets/signin.css 304 34.506 ms - -
GET /stylesheets/sticky-footer.css 304 34.521 ms - -
GET /stylesheets/toastr.min.css 304 35.405 ms - -
GET /javascripts/jquery.min.js 304 36.515 ms - -
GET /javascripts/socket.io-1.4.5.js 304 1.586 ms - -
GET /javascripts/toastr.min.js 304 3.834 ms - -
GET /javascripts/ie10-viewport-bug-workaround.js 304 9.594 ms - -
GET /javascripts/login.js 304 21.776 ms - -
GET /fonts/glyphicons-halflings-regular.woff2 304 0.292 ms - -
GET / 302 1.783 ms - 56
GET /login 304 1.619 ms - -
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:494:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at ServerResponse.header (G:\GitHub\steam-ts\node_modules\express\lib\response.js:767:10)
    at ServerResponse.contentType (G:\GitHub\steam-ts\node_modules\express\lib\response.js:595:15)
    at ServerResponse.send (G:\GitHub\steam-ts\node_modules\express\lib\response.js:145:14)
    at done (G:\GitHub\steam-ts\node_modules\express\lib\response.js:1004:10)
    at View.exports.renderFile [as engine] (G:\GitHub\steam-ts\node_modules\ejs\lib\ejs.js:363:10)
    at View.render (G:\GitHub\steam-ts\node_modules\express\lib\view.js:135:8)
    at tryRender (G:\GitHub\steam-ts\node_modules\express\lib\application.js:640:10)
    at Function.render (G:\GitHub\steam-ts\node_modules\express\lib\application.js:592:3)
GET /stylesheets/bootstrap.min.css 304 13.182 ms - -
GET /stylesheets/ie10-viewport-bug-workaround.css 304 29.147 ms - -
GET /stylesheets/signin.css 304 29.761 ms - -
GET /stylesheets/sticky-footer.css 304 29.526 ms - -
GET /stylesheets/toastr.min.css 304 29.739 ms - -
GET /javascripts/jquery.min.js 304 29.072 ms - -
GET /javascripts/ie10-viewport-bug-workaround.js 304 1.444 ms - -
GET /javascripts/socket.io-1.4.5.js 304 2.026 ms - -
GET /javascripts/toastr.min.js 304 2.651 ms - -
GET /javascripts/login.js 304 3.283 ms - -
GET /fonts/glyphicons-halflings-regular.woff2 304 0.278 ms - -
GET / 302 1.086 ms - 56
GET /login 304 1.931 ms - -
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:494:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at ServerResponse.header (G:\GitHub\steam-ts\node_modules\express\lib\response.js:767:10)
    at ServerResponse.contentType (G:\GitHub\steam-ts\node_modules\express\lib\response.js:595:15)
    at ServerResponse.send (G:\GitHub\steam-ts\node_modules\express\lib\response.js:145:14)
    at done (G:\GitHub\steam-ts\node_modules\express\lib\response.js:1004:10)
    at View.exports.renderFile [as engine] (G:\GitHub\steam-ts\node_modules\ejs\lib\ejs.js:363:10)
    at View.render (G:\GitHub\steam-ts\node_modules\express\lib\view.js:135:8)
    at tryRender (G:\GitHub\steam-ts\node_modules\express\lib\application.js:640:10)
    at Function.render (G:\GitHub\steam-ts\node_modules\express\lib\application.js:592:3)
GET /stylesheets/bootstrap.min.css 304 0.403 ms - -
GET /stylesheets/ie10-viewport-bug-workaround.css 304 5.552 ms - -
GET /stylesheets/signin.css 304 0.595 ms - -
GET /stylesheets/sticky-footer.css 304 1.168 ms - -
GET /stylesheets/toastr.min.css 304 2.158 ms - -
GET /javascripts/jquery.min.js 304 3.184 ms - -
GET /javascripts/ie10-viewport-bug-workaround.js 304 6.441 ms - -
GET /javascripts/socket.io-1.4.5.js 304 7.447 ms - -
GET /javascripts/toastr.min.js 304 8.210 ms - -
GET /javascripts/login.js 304 9.425 ms - -
GET /fonts/glyphicons-halflings-regular.woff2 304 0.276 ms - -
GET / 302 1.053 ms - 56
GET /login 304 1.656 ms - -
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:494:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at ServerResponse.header (G:\GitHub\steam-ts\node_modules\express\lib\response.js:767:10)
    at ServerResponse.contentType (G:\GitHub\steam-ts\node_modules\express\lib\response.js:595:15)
    at ServerResponse.send (G:\GitHub\steam-ts\node_modules\express\lib\response.js:145:14)
    at done (G:\GitHub\steam-ts\node_modules\express\lib\response.js:1004:10)
    at View.exports.renderFile [as engine] (G:\GitHub\steam-ts\node_modules\ejs\lib\ejs.js:363:10)
    at View.render (G:\GitHub\steam-ts\node_modules\express\lib\view.js:135:8)
    at tryRender (G:\GitHub\steam-ts\node_modules\express\lib\application.js:640:10)
    at Function.render (G:\GitHub\steam-ts\node_modules\express\lib\application.js:592:3)
GET /stylesheets/bootstrap.min.css 304 14.206 ms - -
GET /stylesheets/ie10-viewport-bug-workaround.css 304 22.808 ms - -
GET /stylesheets/signin.css 304 23.886 ms - -
GET /stylesheets/sticky-footer.css 304 24.360 ms - -
GET /stylesheets/toastr.min.css 304 24.581 ms - -
GET /javascripts/jquery.min.js 304 24.849 ms - -
GET /javascripts/ie10-viewport-bug-workaround.js 304 1.475 ms - -
GET /javascripts/socket.io-1.4.5.js 304 1.993 ms - -
GET /javascripts/toastr.min.js 304 2.597 ms - -
GET /javascripts/login.js 304 3.180 ms - -
GET /fonts/glyphicons-halflings-regular.woff2 304 0.257 ms - -
Successfully queried users and updated userdata.
Successfully queried users and updated userdata.
GET / 302 0.847 ms - 56
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'G:\GitHub\steam-ts\webserver\sessions\dp2fdHLUddHI5VcN-78MSYs0WDKYZS7W.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'G:\GitHub\steam-ts\webserver\sessions\dp2fdHLUddHI5VcN-78MSYs0WDKYZS7W.json'
GET /login 200 102.486 ms - 2921
GET /stylesheets/ie10-viewport-bug-workaround.css 200 3.771 ms - 534
GET /stylesheets/signin.css 200 4.677 ms - 833
GET /stylesheets/sticky-footer.css 200 6.131 ms - 797
GET /stylesheets/bootstrap.min.css 200 5.203 ms - 121265
GET /stylesheets/toastr.min.css 200 8.207 ms - 5737
GET /javascripts/jquery.min.js 200 10.071 ms - 84384
GET /javascripts/login.js 200 2.296 ms - 3011
GET /javascripts/toastr.min.js 200 3.747 ms - 4323
GET /javascripts/ie10-viewport-bug-workaround.js 200 6.770 ms - 664
GET /javascripts/socket.io-1.4.5.js 200 7.948 ms - 97693
GET /fonts/glyphicons-halflings-regular.woff2 200 0.374 ms - 18028
GET /images/favicon.png 200 0.619 ms - 1492
GET / 302 1.353 ms - 56
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:494:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at ServerResponse.header (G:\GitHub\steam-ts\node_modules\express\lib\response.js:767:10)
    at ServerResponse.send (G:\GitHub\steam-ts\node_modules\express\lib\response.js:170:12)
    at done (G:\GitHub\steam-ts\node_modules\express\lib\response.js:1004:10)
    at View.exports.renderFile [as engine] (G:\GitHub\steam-ts\node_modules\ejs\lib\ejs.js:363:10)
    at View.render (G:\GitHub\steam-ts\node_modules\express\lib\view.js:135:8)
    at tryRender (G:\GitHub\steam-ts\node_modules\express\lib\application.js:640:10)
    at Function.render (G:\GitHub\steam-ts\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (G:\GitHub\steam-ts\node_modules\express\lib\response.js:1008:7)
GET /login 304 1.523 ms - -
GET /stylesheets/bootstrap.min.css 304 1.869 ms - -
GET /stylesheets/ie10-viewport-bug-workaround.css 304 2.626 ms - -
GET /stylesheets/signin.css 304 3.276 ms - -
GET /stylesheets/sticky-footer.css 304 6.127 ms - -
GET /stylesheets/toastr.min.css 304 8.349 ms - -
GET /javascripts/jquery.min.js 304 11.112 ms - -
GET /javascripts/ie10-viewport-bug-workaround.js 304 0.907 ms - -
GET /javascripts/socket.io-1.4.5.js 304 1.303 ms - -
GET /javascripts/toastr.min.js 304 2.092 ms - -
GET /javascripts/login.js 304 2.650 ms - -
GET / 302 1.076 ms - 56
GET /login 304 1.394 ms - -
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:494:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at ServerResponse.header (G:\GitHub\steam-ts\node_modules\express\lib\response.js:767:10)
    at ServerResponse.contentType (G:\GitHub\steam-ts\node_modules\express\lib\response.js:595:15)
    at ServerResponse.send (G:\GitHub\steam-ts\node_modules\express\lib\response.js:145:14)
    at done (G:\GitHub\steam-ts\node_modules\express\lib\response.js:1004:10)
    at View.exports.renderFile [as engine] (G:\GitHub\steam-ts\node_modules\ejs\lib\ejs.js:363:10)
    at View.render (G:\GitHub\steam-ts\node_modules\express\lib\view.js:135:8)
    at tryRender (G:\GitHub\steam-ts\node_modules\express\lib\application.js:640:10)
    at Function.render (G:\GitHub\steam-ts\node_modules\express\lib\application.js:592:3)
GET /stylesheets/bootstrap.min.css 304 1.551 ms - -
GET /stylesheets/ie10-viewport-bug-workaround.css 304 3.991 ms - -
GET /stylesheets/signin.css 304 5.553 ms - -
GET /stylesheets/sticky-footer.css 304 1.331 ms - -
GET /stylesheets/toastr.min.css 304 2.249 ms - -
GET /javascripts/jquery.min.js 304 2.948 ms - -
GET /javascripts/ie10-viewport-bug-workaround.js 304 3.797 ms - -
GET /javascripts/socket.io-1.4.5.js 304 4.177 ms - -
GET /javascripts/toastr.min.js 304 4.520 ms - -
GET /javascripts/login.js 304 3.077 ms - -
GET / 302 1.286 ms - 56
Successfully queried users and updated userdata.
GET /login 304 1.466 ms - -
GET /stylesheets/bootstrap.min.css 304 1.734 ms - -
GET /stylesheets/ie10-viewport-bug-workaround.css 304 5.226 ms - -
GET /stylesheets/signin.css 304 5.656 ms - -
GET /stylesheets/sticky-footer.css 304 6.413 ms - -
GET /stylesheets/toastr.min.css 304 7.882 ms - -
GET /javascripts/jquery.min.js 304 9.157 ms - -
GET /javascripts/ie10-viewport-bug-workaround.js 304 0.752 ms - -
GET /javascripts/socket.io-1.4.5.js 304 1.549 ms - -
GET /javascripts/toastr.min.js 304 3.393 ms - -
GET /javascripts/login.js 304 4.312 ms - -

Windows 10 1809 64 bits

**Comment by rlnt** [comment]
https://github.com/nikitavondel/steam-ts/issues/20#issuecomment-305969878

**Comment by Owned67** [comment]
> [#20 (comment)](https://github.com/nikitavondel/steam-ts/issues/20#issuecomment-305969878)

This doesn't work....

**Comment by rlnt** [comment]
I can't help you more if you just say "can't logged in".

**Comment by Owned67** [comment]
just say?

 i've give log.... I can not log in, the page is reloaded without error and this happens in a loop 


edit: fork https://github.com/xZeroW/steam-ts, i can logged in without problem...

**Comment by rlnt** [comment]
This repository (the fork) is not different from the original one. The guy just filled in his information in the config. It's just random that you can log in this time. As I linked above, for Windows users it's buggy sometimes.

**Comment by Owned67** [comment]
This repository (the fork) is not different from the original one. As I linked above, for Windows users it's buggy sometimes. => but with this fork, i don't have any problem, so strange....
